


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE TYPE "public"."RewardStatus" AS ENUM (
    'PENDING',
    'CLAIMED'
);


ALTER TYPE "public"."RewardStatus" OWNER TO "postgres";


COMMENT ON TYPE "public"."RewardStatus" IS 'Reward statuses';



CREATE OR REPLACE FUNCTION "public"."rls_auto_enable"() RETURNS "event_trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'pg_catalog'
    AS $$
DECLARE
  cmd record;
BEGIN
  FOR cmd IN
    SELECT *
    FROM pg_event_trigger_ddl_commands()
    WHERE command_tag IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
      AND object_type IN ('table','partitioned table')
  LOOP
     IF cmd.schema_name IS NOT NULL AND cmd.schema_name IN ('public') AND cmd.schema_name NOT IN ('pg_catalog','information_schema') AND cmd.schema_name NOT LIKE 'pg_toast%' AND cmd.schema_name NOT LIKE 'pg_temp%' THEN
      BEGIN
        EXECUTE format('alter table if exists %s enable row level security', cmd.object_identity);
        RAISE LOG 'rls_auto_enable: enabled RLS on %', cmd.object_identity;
      EXCEPTION
        WHEN OTHERS THEN
          RAISE LOG 'rls_auto_enable: failed to enable RLS on %', cmd.object_identity;
      END;
     ELSE
        RAISE LOG 'rls_auto_enable: skip % (either system schema or not in enforced list: %.)', cmd.object_identity, cmd.schema_name;
     END IF;
  END LOOP;
END;
$$;


ALTER FUNCTION "public"."rls_auto_enable"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."AffectedStat" (
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "stat_id" bigint NOT NULL,
    "effect_id" bigint NOT NULL
);


ALTER TABLE "public"."AffectedStat" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."Quest" (
    "id" bigint NOT NULL,
    "title" "text" NOT NULL,
    "description" "text",
    "status" character varying DEFAULT 'TODO'::character varying NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "type" "text" NOT NULL,
    "updated_at" timestamp with time zone DEFAULT ("now"() AT TIME ZONE 'utc'::"text") NOT NULL,
    "notes" "text"
);


ALTER TABLE "public"."Quest" OWNER TO "postgres";


ALTER TABLE "public"."Quest" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Quest_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Reward" (
    "id" bigint NOT NULL,
    "title" "text" NOT NULL,
    "description" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "claimed_at" timestamp without time zone,
    "status" "public"."RewardStatus" DEFAULT 'PENDING'::"public"."RewardStatus" NOT NULL,
    "updated_at" timestamp with time zone
);


ALTER TABLE "public"."Reward" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."RewardCost" (
    "reward_id" bigint NOT NULL,
    "token_type" "text" NOT NULL,
    "quantity" bigint DEFAULT '0'::bigint NOT NULL
);


ALTER TABLE "public"."RewardCost" OWNER TO "postgres";


ALTER TABLE "public"."RewardCost" ALTER COLUMN "reward_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."RewardCost_reward_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE "public"."Reward" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Reward_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Stat" (
    "id" bigint NOT NULL,
    "name" "text",
    "value" integer
);


ALTER TABLE "public"."Stat" OWNER TO "postgres";


ALTER TABLE "public"."Stat" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Stat_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."StatusEffect" (
    "id" bigint NOT NULL,
    "text" "text",
    "buff" boolean
);


ALTER TABLE "public"."StatusEffect" OWNER TO "postgres";


ALTER TABLE "public"."StatusEffect" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."StatusEffect_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Task" (
    "id" bigint NOT NULL,
    "title" "text" NOT NULL,
    "description" "text",
    "status" character varying DEFAULT 'TODO'::character varying NOT NULL,
    "notes" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "quest_id" bigint,
    "due_date" "date",
    "completed_at" timestamp with time zone
);


ALTER TABLE "public"."Task" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."TaskOutcome" (
    "task_id" bigint NOT NULL,
    "token_type" "text" NOT NULL,
    "quantity" bigint DEFAULT '0'::bigint NOT NULL
);


ALTER TABLE "public"."TaskOutcome" OWNER TO "postgres";


ALTER TABLE "public"."TaskOutcome" ALTER COLUMN "task_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."TaskOutcome_task_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE "public"."Task" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Task_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Token" (
    "token_type" "text" NOT NULL,
    "quantity" bigint DEFAULT '0'::bigint NOT NULL,
    "icon_filename" "text" NOT NULL,
    "icon_color" "text" NOT NULL
);


ALTER TABLE "public"."Token" OWNER TO "postgres";


ALTER TABLE ONLY "public"."AffectedStat"
    ADD CONSTRAINT "AffectedStat_pkey" PRIMARY KEY ("stat_id", "effect_id");



ALTER TABLE ONLY "public"."Quest"
    ADD CONSTRAINT "Quest_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."RewardCost"
    ADD CONSTRAINT "RewardCost_pkey" PRIMARY KEY ("reward_id", "token_type");



ALTER TABLE ONLY "public"."Reward"
    ADD CONSTRAINT "Reward_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Stat"
    ADD CONSTRAINT "Stat_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."StatusEffect"
    ADD CONSTRAINT "StatusEffect_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."TaskOutcome"
    ADD CONSTRAINT "TaskOutcome_pkey" PRIMARY KEY ("task_id", "token_type");



ALTER TABLE ONLY "public"."Task"
    ADD CONSTRAINT "Task_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Token"
    ADD CONSTRAINT "Token_pkey" PRIMARY KEY ("token_type");



ALTER TABLE ONLY "public"."AffectedStat"
    ADD CONSTRAINT "AffectedStat_effect_id_fkey" FOREIGN KEY ("effect_id") REFERENCES "public"."StatusEffect"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."AffectedStat"
    ADD CONSTRAINT "AffectedStat_stat_id_fkey" FOREIGN KEY ("stat_id") REFERENCES "public"."Stat"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."RewardCost"
    ADD CONSTRAINT "RewardCost_reward_id_fkey" FOREIGN KEY ("reward_id") REFERENCES "public"."Reward"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."RewardCost"
    ADD CONSTRAINT "RewardCost_token_type_fkey" FOREIGN KEY ("token_type") REFERENCES "public"."Token"("token_type") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."TaskOutcome"
    ADD CONSTRAINT "TaskOutcome_task_id_fkey" FOREIGN KEY ("task_id") REFERENCES "public"."Task"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."TaskOutcome"
    ADD CONSTRAINT "TaskOutcome_token_type_fkey" FOREIGN KEY ("token_type") REFERENCES "public"."Token"("token_type") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."Task"
    ADD CONSTRAINT "Task_quest_id_fkey" FOREIGN KEY ("quest_id") REFERENCES "public"."Quest"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE "public"."AffectedStat" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "Only authenticated human user can delete rows in table" ON "public"."AffectedStat" FOR DELETE TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") IS NOT NULL));



CREATE POLICY "Only authenticated human user can delete rows in table" ON "public"."Quest" FOR DELETE TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") IS NOT NULL));



CREATE POLICY "Only authenticated human user can delete rows in table" ON "public"."Reward" FOR DELETE TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") IS NOT NULL));



CREATE POLICY "Only authenticated human user can delete rows in table" ON "public"."RewardCost" FOR DELETE TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") IS NOT NULL));



CREATE POLICY "Only authenticated human user can delete rows in table" ON "public"."Stat" FOR DELETE TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") IS NOT NULL));



CREATE POLICY "Only authenticated human user can delete rows in table" ON "public"."StatusEffect" FOR DELETE TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") IS NOT NULL));



CREATE POLICY "Only authenticated human user can delete rows in table" ON "public"."Task" FOR DELETE TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") IS NOT NULL));



CREATE POLICY "Only authenticated human user can delete rows in table" ON "public"."TaskOutcome" FOR DELETE TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") IS NOT NULL));



CREATE POLICY "Only authenticated human user can delete rows in table" ON "public"."Token" FOR DELETE TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") IS NOT NULL));



CREATE POLICY "Only authenticated human user can read table" ON "public"."AffectedStat" FOR SELECT TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") IS NOT NULL));



CREATE POLICY "Only authenticated human user can read table" ON "public"."Quest" FOR SELECT TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") IS NOT NULL));



CREATE POLICY "Only authenticated human user can read table" ON "public"."Reward" FOR SELECT TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") IS NOT NULL));



CREATE POLICY "Only authenticated human user can read table" ON "public"."RewardCost" FOR SELECT TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") IS NOT NULL));



CREATE POLICY "Only authenticated human user can read table" ON "public"."Stat" FOR SELECT TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") IS NOT NULL));



CREATE POLICY "Only authenticated human user can read table" ON "public"."StatusEffect" FOR SELECT TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") IS NOT NULL));



CREATE POLICY "Only authenticated human user can read table" ON "public"."Task" FOR SELECT TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") IS NOT NULL));



CREATE POLICY "Only authenticated human user can read table" ON "public"."TaskOutcome" FOR SELECT TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") IS NOT NULL));



CREATE POLICY "Only authenticated human user can read table" ON "public"."Token" FOR SELECT TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") IS NOT NULL));



CREATE POLICY "Only authenticated human user can update rows in table" ON "public"."AffectedStat" FOR UPDATE TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") IS NOT NULL)) WITH CHECK ((( SELECT "auth"."uid"() AS "uid") IS NOT NULL));



CREATE POLICY "Only authenticated human user can update rows in table" ON "public"."Quest" FOR UPDATE TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") IS NOT NULL)) WITH CHECK ((( SELECT "auth"."uid"() AS "uid") IS NOT NULL));



CREATE POLICY "Only authenticated human user can update rows in table" ON "public"."Reward" FOR UPDATE TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") IS NOT NULL)) WITH CHECK ((( SELECT "auth"."uid"() AS "uid") IS NOT NULL));



CREATE POLICY "Only authenticated human user can update rows in table" ON "public"."RewardCost" FOR UPDATE TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") IS NOT NULL)) WITH CHECK ((( SELECT "auth"."uid"() AS "uid") IS NOT NULL));



CREATE POLICY "Only authenticated human user can update rows in table" ON "public"."Stat" FOR UPDATE TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") IS NOT NULL)) WITH CHECK ((( SELECT "auth"."uid"() AS "uid") IS NOT NULL));



CREATE POLICY "Only authenticated human user can update rows in table" ON "public"."StatusEffect" FOR UPDATE TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") IS NOT NULL)) WITH CHECK ((( SELECT "auth"."uid"() AS "uid") IS NOT NULL));



CREATE POLICY "Only authenticated human user can update rows in table" ON "public"."Task" FOR UPDATE TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") IS NOT NULL)) WITH CHECK ((( SELECT "auth"."uid"() AS "uid") IS NOT NULL));



CREATE POLICY "Only authenticated human user can update rows in table" ON "public"."TaskOutcome" FOR UPDATE TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") IS NOT NULL)) WITH CHECK ((( SELECT "auth"."uid"() AS "uid") IS NOT NULL));



CREATE POLICY "Only authenticated human user can update rows in table" ON "public"."Token" FOR UPDATE TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") IS NOT NULL)) WITH CHECK ((( SELECT "auth"."uid"() AS "uid") IS NOT NULL));



CREATE POLICY "Only authenticated human user can write to table" ON "public"."AffectedStat" FOR INSERT TO "authenticated" WITH CHECK ((( SELECT "auth"."uid"() AS "uid") IS NOT NULL));



CREATE POLICY "Only authenticated human user can write to table" ON "public"."Quest" FOR INSERT TO "authenticated" WITH CHECK ((( SELECT "auth"."uid"() AS "uid") IS NOT NULL));



CREATE POLICY "Only authenticated human user can write to table" ON "public"."Reward" FOR INSERT TO "authenticated" WITH CHECK ((( SELECT "auth"."uid"() AS "uid") IS NOT NULL));



CREATE POLICY "Only authenticated human user can write to table" ON "public"."RewardCost" FOR INSERT TO "authenticated" WITH CHECK ((( SELECT "auth"."uid"() AS "uid") IS NOT NULL));



CREATE POLICY "Only authenticated human user can write to table" ON "public"."Stat" FOR INSERT TO "authenticated" WITH CHECK ((( SELECT "auth"."uid"() AS "uid") IS NOT NULL));



CREATE POLICY "Only authenticated human user can write to table" ON "public"."StatusEffect" FOR INSERT TO "authenticated" WITH CHECK ((( SELECT "auth"."uid"() AS "uid") IS NOT NULL));



CREATE POLICY "Only authenticated human user can write to table" ON "public"."Task" FOR INSERT TO "authenticated" WITH CHECK ((( SELECT "auth"."uid"() AS "uid") IS NOT NULL));



CREATE POLICY "Only authenticated human user can write to table" ON "public"."TaskOutcome" FOR INSERT TO "authenticated" WITH CHECK ((( SELECT "auth"."uid"() AS "uid") IS NOT NULL));



CREATE POLICY "Only authenticated human user can write to table" ON "public"."Token" FOR INSERT TO "authenticated" WITH CHECK ((( SELECT "auth"."uid"() AS "uid") IS NOT NULL));



ALTER TABLE "public"."Quest" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Reward" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."RewardCost" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Stat" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."StatusEffect" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Task" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."TaskOutcome" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Token" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

























































































































































GRANT ALL ON FUNCTION "public"."rls_auto_enable"() TO "anon";
GRANT ALL ON FUNCTION "public"."rls_auto_enable"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."rls_auto_enable"() TO "service_role";


















GRANT ALL ON TABLE "public"."AffectedStat" TO "anon";
GRANT ALL ON TABLE "public"."AffectedStat" TO "authenticated";
GRANT ALL ON TABLE "public"."AffectedStat" TO "service_role";



GRANT ALL ON TABLE "public"."Quest" TO "anon";
GRANT ALL ON TABLE "public"."Quest" TO "authenticated";
GRANT ALL ON TABLE "public"."Quest" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Quest_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Quest_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Quest_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Reward" TO "anon";
GRANT ALL ON TABLE "public"."Reward" TO "authenticated";
GRANT ALL ON TABLE "public"."Reward" TO "service_role";



GRANT ALL ON TABLE "public"."RewardCost" TO "anon";
GRANT ALL ON TABLE "public"."RewardCost" TO "authenticated";
GRANT ALL ON TABLE "public"."RewardCost" TO "service_role";



GRANT ALL ON SEQUENCE "public"."RewardCost_reward_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."RewardCost_reward_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."RewardCost_reward_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Reward_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Reward_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Reward_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Stat" TO "anon";
GRANT ALL ON TABLE "public"."Stat" TO "authenticated";
GRANT ALL ON TABLE "public"."Stat" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Stat_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Stat_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Stat_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."StatusEffect" TO "anon";
GRANT ALL ON TABLE "public"."StatusEffect" TO "authenticated";
GRANT ALL ON TABLE "public"."StatusEffect" TO "service_role";



GRANT ALL ON SEQUENCE "public"."StatusEffect_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."StatusEffect_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."StatusEffect_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Task" TO "anon";
GRANT ALL ON TABLE "public"."Task" TO "authenticated";
GRANT ALL ON TABLE "public"."Task" TO "service_role";



GRANT ALL ON TABLE "public"."TaskOutcome" TO "anon";
GRANT ALL ON TABLE "public"."TaskOutcome" TO "authenticated";
GRANT ALL ON TABLE "public"."TaskOutcome" TO "service_role";



GRANT ALL ON SEQUENCE "public"."TaskOutcome_task_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."TaskOutcome_task_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."TaskOutcome_task_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Task_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Task_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Task_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Token" TO "anon";
GRANT ALL ON TABLE "public"."Token" TO "authenticated";
GRANT ALL ON TABLE "public"."Token" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";



































drop extension if exists "pg_net";


