
  create table "public"."TransactionType" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "kind" text not null,
    "description" text,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."TransactionType" enable row level security;


  create table "public"."Transaction" (
    "id" bigint generated by default as identity not null,
    "amount" numeric(12,2) not null,
    "transaction_type_id" bigint not null,
    "description" text not null,
    "date" timestamp with time zone not null,
    "created_at" timestamp with time zone not null default now(),
    "source" text not null default 'manual'
      );


alter table "public"."Transaction" enable row level security;


  create table "public"."Budget" (
    "id" bigint generated by default as identity not null,
    "transaction_type_id" bigint not null,
    "amount" numeric(12,2) not null,
    "period" text not null,
    "start_date" timestamp with time zone not null,
    "end_date" timestamp with time zone,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."Budget" enable row level security;


  create table "public"."UserQuery" (
    "id" bigint generated by default as identity not null,
    "query_text" text not null,
    "response_text" text not null,
    "resolved_transaction_ids" bigint[],
    "date_range_context" jsonb,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."UserQuery" enable row level security;

CREATE UNIQUE INDEX "TransactionType_pkey" ON public."TransactionType" USING btree (id);

CREATE UNIQUE INDEX "Transaction_pkey" ON public."Transaction" USING btree (id);

CREATE UNIQUE INDEX "Budget_pkey" ON public."Budget" USING btree (id);

CREATE UNIQUE INDEX "UserQuery_pkey" ON public."UserQuery" USING btree (id);

CREATE INDEX "Transaction_transaction_type_id_idx" ON public."Transaction" USING btree (transaction_type_id);

CREATE INDEX "Transaction_date_idx" ON public."Transaction" USING btree (date);

CREATE INDEX "Budget_transaction_type_id_idx" ON public."Budget" USING btree (transaction_type_id);

alter table "public"."TransactionType" add constraint "TransactionType_pkey" PRIMARY KEY using index "TransactionType_pkey";

alter table "public"."Transaction" add constraint "Transaction_pkey" PRIMARY KEY using index "Transaction_pkey";

alter table "public"."Budget" add constraint "Budget_pkey" PRIMARY KEY using index "Budget_pkey";

alter table "public"."UserQuery" add constraint "UserQuery_pkey" PRIMARY KEY using index "UserQuery_pkey";

alter table "public"."Transaction" add constraint "Transaction_transaction_type_id_fkey" FOREIGN KEY (transaction_type_id) REFERENCES public."TransactionType"(id) ON UPDATE CASCADE ON DELETE RESTRICT not valid;

alter table "public"."Transaction" validate constraint "Transaction_transaction_type_id_fkey";

alter table "public"."Budget" add constraint "Budget_transaction_type_id_fkey" FOREIGN KEY (transaction_type_id) REFERENCES public."TransactionType"(id) ON UPDATE CASCADE ON DELETE RESTRICT not valid;

alter table "public"."Budget" validate constraint "Budget_transaction_type_id_fkey";

grant delete on table "public"."TransactionType" to "anon";

grant insert on table "public"."TransactionType" to "anon";

grant references on table "public"."TransactionType" to "anon";

grant select on table "public"."TransactionType" to "anon";

grant trigger on table "public"."TransactionType" to "anon";

grant truncate on table "public"."TransactionType" to "anon";

grant update on table "public"."TransactionType" to "anon";

grant delete on table "public"."TransactionType" to "authenticated";

grant insert on table "public"."TransactionType" to "authenticated";

grant references on table "public"."TransactionType" to "authenticated";

grant select on table "public"."TransactionType" to "authenticated";

grant trigger on table "public"."TransactionType" to "authenticated";

grant truncate on table "public"."TransactionType" to "authenticated";

grant update on table "public"."TransactionType" to "authenticated";

grant delete on table "public"."TransactionType" to "service_role";

grant insert on table "public"."TransactionType" to "service_role";

grant references on table "public"."TransactionType" to "service_role";

grant select on table "public"."TransactionType" to "service_role";

grant trigger on table "public"."TransactionType" to "service_role";

grant truncate on table "public"."TransactionType" to "service_role";

grant update on table "public"."TransactionType" to "service_role";

grant delete on table "public"."Transaction" to "anon";

grant insert on table "public"."Transaction" to "anon";

grant references on table "public"."Transaction" to "anon";

grant select on table "public"."Transaction" to "anon";

grant trigger on table "public"."Transaction" to "anon";

grant truncate on table "public"."Transaction" to "anon";

grant update on table "public"."Transaction" to "anon";

grant delete on table "public"."Transaction" to "authenticated";

grant insert on table "public"."Transaction" to "authenticated";

grant references on table "public"."Transaction" to "authenticated";

grant select on table "public"."Transaction" to "authenticated";

grant trigger on table "public"."Transaction" to "authenticated";

grant truncate on table "public"."Transaction" to "authenticated";

grant update on table "public"."Transaction" to "authenticated";

grant delete on table "public"."Transaction" to "service_role";

grant insert on table "public"."Transaction" to "service_role";

grant references on table "public"."Transaction" to "service_role";

grant select on table "public"."Transaction" to "service_role";

grant trigger on table "public"."Transaction" to "service_role";

grant truncate on table "public"."Transaction" to "service_role";

grant update on table "public"."Transaction" to "service_role";

grant delete on table "public"."Budget" to "anon";

grant insert on table "public"."Budget" to "anon";

grant references on table "public"."Budget" to "anon";

grant select on table "public"."Budget" to "anon";

grant trigger on table "public"."Budget" to "anon";

grant truncate on table "public"."Budget" to "anon";

grant update on table "public"."Budget" to "anon";

grant delete on table "public"."Budget" to "authenticated";

grant insert on table "public"."Budget" to "authenticated";

grant references on table "public"."Budget" to "authenticated";

grant select on table "public"."Budget" to "authenticated";

grant trigger on table "public"."Budget" to "authenticated";

grant truncate on table "public"."Budget" to "authenticated";

grant update on table "public"."Budget" to "authenticated";

grant delete on table "public"."Budget" to "service_role";

grant insert on table "public"."Budget" to "service_role";

grant references on table "public"."Budget" to "service_role";

grant select on table "public"."Budget" to "service_role";

grant trigger on table "public"."Budget" to "service_role";

grant truncate on table "public"."Budget" to "service_role";

grant update on table "public"."Budget" to "service_role";

grant delete on table "public"."UserQuery" to "anon";

grant insert on table "public"."UserQuery" to "anon";

grant references on table "public"."UserQuery" to "anon";

grant select on table "public"."UserQuery" to "anon";

grant trigger on table "public"."UserQuery" to "anon";

grant truncate on table "public"."UserQuery" to "anon";

grant update on table "public"."UserQuery" to "anon";

grant delete on table "public"."UserQuery" to "authenticated";

grant insert on table "public"."UserQuery" to "authenticated";

grant references on table "public"."UserQuery" to "authenticated";

grant select on table "public"."UserQuery" to "authenticated";

grant trigger on table "public"."UserQuery" to "authenticated";

grant truncate on table "public"."UserQuery" to "authenticated";

grant update on table "public"."UserQuery" to "authenticated";

grant delete on table "public"."UserQuery" to "service_role";

grant insert on table "public"."UserQuery" to "service_role";

grant references on table "public"."UserQuery" to "service_role";

grant select on table "public"."UserQuery" to "service_role";

grant trigger on table "public"."UserQuery" to "service_role";

grant truncate on table "public"."UserQuery" to "service_role";

grant update on table "public"."UserQuery" to "service_role";


  create policy "Only authenticated human users can delete rows in table"
  on "public"."TransactionType"
  as permissive
  for delete
  to authenticated
using ((( SELECT auth.uid() AS uid) IS NOT NULL));



  create policy "Only authenticated human users can read table"
  on "public"."TransactionType"
  as permissive
  for select
  to authenticated
using ((( SELECT auth.uid() AS uid) IS NOT NULL));



  create policy "Only authenticated human users can update table"
  on "public"."TransactionType"
  as permissive
  for update
  to authenticated
using ((( SELECT auth.uid() AS uid) IS NOT NULL))
with check ((( SELECT auth.uid() AS uid) IS NOT NULL));



  create policy "Only authenticated human users can write to table"
  on "public"."TransactionType"
  as permissive
  for insert
  to authenticated
with check ((( SELECT auth.uid() AS uid) IS NOT NULL));



  create policy "Only authenticated human users can delete rows in table"
  on "public"."Transaction"
  as permissive
  for delete
  to authenticated
using ((( SELECT auth.uid() AS uid) IS NOT NULL));



  create policy "Only authenticated human users can read table"
  on "public"."Transaction"
  as permissive
  for select
  to authenticated
using ((( SELECT auth.uid() AS uid) IS NOT NULL));



  create policy "Only authenticated human users can update table"
  on "public"."Transaction"
  as permissive
  for update
  to authenticated
using ((( SELECT auth.uid() AS uid) IS NOT NULL))
with check ((( SELECT auth.uid() AS uid) IS NOT NULL));



  create policy "Only authenticated human users can write to table"
  on "public"."Transaction"
  as permissive
  for insert
  to authenticated
with check ((( SELECT auth.uid() AS uid) IS NOT NULL));



  create policy "Only authenticated human users can delete rows in table"
  on "public"."Budget"
  as permissive
  for delete
  to authenticated
using ((( SELECT auth.uid() AS uid) IS NOT NULL));



  create policy "Only authenticated human users can read table"
  on "public"."Budget"
  as permissive
  for select
  to authenticated
using ((( SELECT auth.uid() AS uid) IS NOT NULL));



  create policy "Only authenticated human users can update table"
  on "public"."Budget"
  as permissive
  for update
  to authenticated
using ((( SELECT auth.uid() AS uid) IS NOT NULL))
with check ((( SELECT auth.uid() AS uid) IS NOT NULL));



  create policy "Only authenticated human users can write to table"
  on "public"."Budget"
  as permissive
  for insert
  to authenticated
with check ((( SELECT auth.uid() AS uid) IS NOT NULL));



  create policy "Only authenticated human users can delete rows in table"
  on "public"."UserQuery"
  as permissive
  for delete
  to authenticated
using ((( SELECT auth.uid() AS uid) IS NOT NULL));



  create policy "Only authenticated human users can read table"
  on "public"."UserQuery"
  as permissive
  for select
  to authenticated
using ((( SELECT auth.uid() AS uid) IS NOT NULL));



  create policy "Only authenticated human users can update table"
  on "public"."UserQuery"
  as permissive
  for update
  to authenticated
using ((( SELECT auth.uid() AS uid) IS NOT NULL))
with check ((( SELECT auth.uid() AS uid) IS NOT NULL));



  create policy "Only authenticated human users can write to table"
  on "public"."UserQuery"
  as permissive
  for insert
  to authenticated
with check ((( SELECT auth.uid() AS uid) IS NOT NULL));



insert into "public"."TransactionType" (name, kind)
values
  ('Need', 'expense'),
  ('Want', 'expense'),
  ('Investment', 'expense'),
  ('Income', 'income');

