
  create table "public"."QuestTag" (
    "tag_id" bigint not null,
    "quest_id" bigint not null
      );


alter table "public"."QuestTag" enable row level security;


  create table "public"."Tag" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "color" text not null,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."Tag" enable row level security;


  create table "public"."TaskTag" (
    "tag_id" bigint not null,
    "task_id" bigint not null
      );


alter table "public"."TaskTag" enable row level security;

CREATE UNIQUE INDEX "QuestTag_pkey" ON public."QuestTag" USING btree (tag_id, quest_id);

CREATE UNIQUE INDEX "Tag_pkey" ON public."Tag" USING btree (id);

CREATE UNIQUE INDEX "TaskTag_pkey" ON public."TaskTag" USING btree (tag_id, task_id);

alter table "public"."QuestTag" add constraint "QuestTag_pkey" PRIMARY KEY using index "QuestTag_pkey";

alter table "public"."Tag" add constraint "Tag_pkey" PRIMARY KEY using index "Tag_pkey";

alter table "public"."TaskTag" add constraint "TaskTag_pkey" PRIMARY KEY using index "TaskTag_pkey";

alter table "public"."QuestTag" add constraint "QuestTag_quest_id_fkey" FOREIGN KEY (quest_id) REFERENCES public."Quest"(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."QuestTag" validate constraint "QuestTag_quest_id_fkey";

alter table "public"."QuestTag" add constraint "QuestTag_tag_id_fkey" FOREIGN KEY (tag_id) REFERENCES public."Tag"(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."QuestTag" validate constraint "QuestTag_tag_id_fkey";

alter table "public"."TaskTag" add constraint "TaskTag_tag_id_fkey" FOREIGN KEY (tag_id) REFERENCES public."Tag"(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."TaskTag" validate constraint "TaskTag_tag_id_fkey";

alter table "public"."TaskTag" add constraint "TaskTag_task_id_fkey" FOREIGN KEY (task_id) REFERENCES public."Task"(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."TaskTag" validate constraint "TaskTag_task_id_fkey";

grant delete on table "public"."QuestTag" to "anon";

grant insert on table "public"."QuestTag" to "anon";

grant references on table "public"."QuestTag" to "anon";

grant select on table "public"."QuestTag" to "anon";

grant trigger on table "public"."QuestTag" to "anon";

grant truncate on table "public"."QuestTag" to "anon";

grant update on table "public"."QuestTag" to "anon";

grant delete on table "public"."QuestTag" to "authenticated";

grant insert on table "public"."QuestTag" to "authenticated";

grant references on table "public"."QuestTag" to "authenticated";

grant select on table "public"."QuestTag" to "authenticated";

grant trigger on table "public"."QuestTag" to "authenticated";

grant truncate on table "public"."QuestTag" to "authenticated";

grant update on table "public"."QuestTag" to "authenticated";

grant delete on table "public"."QuestTag" to "service_role";

grant insert on table "public"."QuestTag" to "service_role";

grant references on table "public"."QuestTag" to "service_role";

grant select on table "public"."QuestTag" to "service_role";

grant trigger on table "public"."QuestTag" to "service_role";

grant truncate on table "public"."QuestTag" to "service_role";

grant update on table "public"."QuestTag" to "service_role";

grant delete on table "public"."Tag" to "anon";

grant insert on table "public"."Tag" to "anon";

grant references on table "public"."Tag" to "anon";

grant select on table "public"."Tag" to "anon";

grant trigger on table "public"."Tag" to "anon";

grant truncate on table "public"."Tag" to "anon";

grant update on table "public"."Tag" to "anon";

grant delete on table "public"."Tag" to "authenticated";

grant insert on table "public"."Tag" to "authenticated";

grant references on table "public"."Tag" to "authenticated";

grant select on table "public"."Tag" to "authenticated";

grant trigger on table "public"."Tag" to "authenticated";

grant truncate on table "public"."Tag" to "authenticated";

grant update on table "public"."Tag" to "authenticated";

grant delete on table "public"."Tag" to "service_role";

grant insert on table "public"."Tag" to "service_role";

grant references on table "public"."Tag" to "service_role";

grant select on table "public"."Tag" to "service_role";

grant trigger on table "public"."Tag" to "service_role";

grant truncate on table "public"."Tag" to "service_role";

grant update on table "public"."Tag" to "service_role";

grant delete on table "public"."TaskTag" to "anon";

grant insert on table "public"."TaskTag" to "anon";

grant references on table "public"."TaskTag" to "anon";

grant select on table "public"."TaskTag" to "anon";

grant trigger on table "public"."TaskTag" to "anon";

grant truncate on table "public"."TaskTag" to "anon";

grant update on table "public"."TaskTag" to "anon";

grant delete on table "public"."TaskTag" to "authenticated";

grant insert on table "public"."TaskTag" to "authenticated";

grant references on table "public"."TaskTag" to "authenticated";

grant select on table "public"."TaskTag" to "authenticated";

grant trigger on table "public"."TaskTag" to "authenticated";

grant truncate on table "public"."TaskTag" to "authenticated";

grant update on table "public"."TaskTag" to "authenticated";

grant delete on table "public"."TaskTag" to "service_role";

grant insert on table "public"."TaskTag" to "service_role";

grant references on table "public"."TaskTag" to "service_role";

grant select on table "public"."TaskTag" to "service_role";

grant trigger on table "public"."TaskTag" to "service_role";

grant truncate on table "public"."TaskTag" to "service_role";

grant update on table "public"."TaskTag" to "service_role";


  create policy "Only authenticated human users can delete rows in table"
  on "public"."QuestTag"
  as permissive
  for delete
  to authenticated
using ((( SELECT auth.uid() AS uid) IS NOT NULL));



  create policy "Only authenticated human users can read table"
  on "public"."QuestTag"
  as permissive
  for select
  to authenticated
using ((( SELECT auth.uid() AS uid) IS NOT NULL));



  create policy "Only authenticated human users can update table"
  on "public"."QuestTag"
  as permissive
  for update
  to authenticated
using ((( SELECT auth.uid() AS uid) IS NOT NULL))
with check ((( SELECT auth.uid() AS uid) IS NOT NULL));



  create policy "Only authenticated human users can write to table"
  on "public"."QuestTag"
  as permissive
  for insert
  to authenticated
with check ((( SELECT auth.uid() AS uid) IS NOT NULL));



  create policy "Only authenticated human users can delete rows in table"
  on "public"."Tag"
  as permissive
  for delete
  to authenticated
using ((( SELECT auth.uid() AS uid) IS NOT NULL));



  create policy "Only authenticated human users can read table"
  on "public"."Tag"
  as permissive
  for select
  to authenticated
using ((( SELECT auth.uid() AS uid) IS NOT NULL));



  create policy "Only authenticated human users can update table"
  on "public"."Tag"
  as permissive
  for update
  to authenticated
using ((( SELECT auth.uid() AS uid) IS NOT NULL))
with check ((( SELECT auth.uid() AS uid) IS NOT NULL));



  create policy "Only authenticated human users can write to table"
  on "public"."Tag"
  as permissive
  for insert
  to authenticated
with check ((( SELECT auth.uid() AS uid) IS NOT NULL));



  create policy "Only authenticated human users can delete rows in table"
  on "public"."TaskTag"
  as permissive
  for delete
  to authenticated
using ((( SELECT auth.uid() AS uid) IS NOT NULL));



  create policy "Only authenticated human users can read table"
  on "public"."TaskTag"
  as permissive
  for select
  to authenticated
using ((( SELECT auth.uid() AS uid) IS NOT NULL));



  create policy "Only authenticated human users can update table"
  on "public"."TaskTag"
  as permissive
  for update
  to authenticated
using ((( SELECT auth.uid() AS uid) IS NOT NULL))
with check ((( SELECT auth.uid() AS uid) IS NOT NULL));



  create policy "Only authenticated human users can write to table"
  on "public"."TaskTag"
  as permissive
  for insert
  to authenticated
with check ((( SELECT auth.uid() AS uid) IS NOT NULL));



